// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqlvmmvtskdevdsvzqiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxbHZtbXZ0c2tkZXZkc3Z6cWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NzQ3ODIsImV4cCI6MjA3MTE1MDc4Mn0.y1Azv4A2foh0SvfugubLzjB3jpIF-t6CGBo7vV_R8cw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});